language: java
sudo: true
jdk: oraclejdk8
services:
  - docker
  
before_install:
  - chmod +x mvnw
  
script:
- ./mvnw clean test -B

after_success:
  - ./mvnw package -Pprod verify jib:dockerBuild
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push himadrica/taskapplication
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: jhipster-taskApplication
  env: JhipsterTaskapplication-env
  bucket_name: "elasticbeanstalk-us-east-2-411339812211"
  bucket_path: task-application
  local_dir: "target"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY